version: "3"
services:
  react-app:
    build: ./frontend
    image: react-app
    stdin_open: true
    ports: 
      - "3000:5173"
    networks:
      - mern-app
  api-server:
    build: ./backend
    image: api-server
    ports:
      - "5555:5555"
    networks:
      - mern-app
networks:
  mern-app:
    driver: bridge